// @helena/sdk: the contracts of Helena's extension points and a small registry core.
// This entry is isomorphic (API, worker, runner, web) and has no runtime dependencies
// beyond itself. Server-only pieces (plugin host, loader, manifest validation, the event
// outbox dispatcher) are in '@helena/sdk/server'; the web's slot registry in
// '@helena/sdk/web'.

export { SDK_VERSION } from './version';
export {
  CORE_PLUGIN_ID,
  Registry,
  RegistryError,
  createRegistry,
  type RegistryEntry,
} from './registry';
export { createRegistries, type HelenaRegistries } from './registries';
export {
  ACTION_CATEGORIES,
  ACTION_META_KEY,
  actionRank,
  annotationsForCategory,
  categoryFromAcpToolKind,
  categoryFromAnnotations,
  isActionCategory,
  type ActionCategory,
  type ActionScope,
} from './actions';
export { consoleLogger, type AgentRef, type Logger, type ProjectRef } from './common';
export { MIN_SECRET_LENGTH, SECRET_MASK, SecretMask, SecretStream } from './secret-mask';
export { resolveText, type LocalizedText, type Translate } from './text';
export {
  SchemaError,
  isStandardSchema,
  toJsonSchema,
  validate,
  type JsonSchema,
  type SchemaLike,
} from './schema';
export {
  TOOL_NAME,
  declaredCategory,
  isCallToolResult,
  toCallToolResult,
  toMcpTool,
  toolCategory,
  toolDescriptor,
  toolError,
  type AgentTool,
  type AnyAgentTool,
  type CallerAuth,
  type ToolCallContext,
  type ToolDescriptor,
} from './tools';
export {
  CredentialError,
  coerceCredential,
  redactCredential,
  type Connector,
  type ConnectorAuth,
  type ConnectorAuthContext,
  type ConnectorAuthStep,
  type ConnectorHealth,
  type ConnectorService,
  type CredentialField,
  type CredentialFieldType,
  type CredentialValues,
} from './connectors';
export type {
  StepExecutionContext,
  StepIssue,
  StepOutcome,
  StepRun,
  StepSignal,
  StepUiHints,
  StepValidationContext,
  TriggerMatch,
  TriggerType,
  WorkflowStepType,
} from './workflows';
export {
  DEFAULT_DECISION,
  decide,
  type PolicyContext,
  type PolicyDecision,
  type PolicyEffect,
  type PolicyEvaluator,
  type PolicyRequest,
} from './policy';
export {
  CORE_EVENT_TYPES,
  createEvent,
  createEventBus,
  eventSource,
  matchesEventPattern,
  type ApprovalEventData,
  type CommentRef,
  type CoreEvent,
  type CoreEventData,
  type CoreEventType,
  type EventBus,
  type EventBusOptions,
  type EventHandler,
  type EventInit,
  type EventSubscription,
  type EventTransport,
  type HelenaEvent,
  type IssueRef,
  type RunEventData,
} from './events';
export type {
  CaptureContext,
  CaptureInput,
  CaptureKind,
  CaptureResult,
  CaptureTarget,
  KnowledgeItem,
  KnowledgeLink,
  KnowledgeLinkKind,
  KnowledgeListContext,
  KnowledgeMetadataValue,
  KnowledgeProvenance,
  KnowledgeScope,
  KnowledgeSource,
} from './knowledge';
export {
  cliArgv,
  cliPrompt,
  type AcpLaunch,
  type AcpRuntimeType,
  type CliCommand,
  type CliRuntimeType,
  type RuntimeAdapterContext,
  type RuntimeCapabilities,
  type RuntimeStreamEvent,
  type RuntimeStreamParser,
  type RuntimeTaskSettings,
  type RuntimeType,
} from './runtime';
export {
  classifyProviderFailure,
  FAILURE_DETAIL_LIMIT,
  isFinalFailure,
  type RuntimeFailure,
  type RuntimeFailureCode,
  type RuntimeFailureInput,
} from './runtime-failures';
export {
  canonicalJson,
  resolveMcpValue,
  runModelReport,
  templateOf,
  type DriftCode,
  type McpNamedValue,
  type McpServerSpec,
  type McpValue,
  type ProfileDrift,
  type ProfileMcpServer,
  type CommandHooks,
  type CommandSandbox,
  type ProfileReport,
  type RunModelReport,
  type RunSettings,
  type RuntimeAdapter,
  type RuntimeDefaults,
  type RuntimeId,
  type RuntimeIssue,
  type RuntimeIssueCode,
  type SessionFacts,
  type StartGate,
  type WorkRef,
} from './runtime-profile';
export type {
  HermesProfile,
  MemoryFile,
  ProfileContext,
  ProfileContribution,
  RuntimeAction,
  RuntimeCompression,
  RuntimeHermesSettings,
  RuntimeHelenaSettings,
  RuntimeLearning,
  RuntimeMcpServer,
  RuntimeMcpValue,
  RuntimeMemoryPolicy,
  RuntimePolicyFile,
  RuntimePolicySnapshot,
  RuntimeSkill,
  RuntimeSkillFile,
  VaultAccess,
} from './runtime-policy';
export {
  REQUEST_CAPABILITY,
  type CuratorStatus,
  type GenAiUsage,
  type LogLines,
  type ReaderContext,
  type RuntimeHealth,
  type RuntimeReaders,
  type RuntimeRequest,
  type RuntimeRequestOp,
  type RuntimeVersion,
  type SessionPage,
  type SessionSearchHit,
  type SessionSummary,
  type Transcript,
  type TranscriptMessage,
  type TranscriptPart,
} from './runtime-readers';
export {
  sortSlots,
  uiSlotDescriptor,
  uiSlotKey,
  type AdminSectionSlot,
  type ServerSectionSlot,
  type AgentSectionProps,
  type AgentSectionSlot,
  type CaptureActionSlot,
  type ComponentRender,
  type DashboardAudience,
  type DashboardSurface,
  type DashboardWidgetKind,
  type DashboardWidgetProps,
  type DashboardWidgetSlot,
  type FrameRender,
  type HeaderActionSlot,
  type HomeNavSlot,
  type PanelToolProps,
  type PanelToolSlot,
  type ProjectSettingsProps,
  type ProjectSettingsSlot,
  type SlotComponent,
  type SlotOf,
  type SlotRender,
  type UiSlot,
  type UiSlotDescriptor,
  type UiSlotName,
  type WorkspaceLayoutArea,
  type WorkspaceLayoutSlot,
} from './ui';
export {
  ACCEPTED_LICENSES,
  BUNDLE_FORMAT,
  BUNDLE_FORMAT_VERSION,
  BUNDLE_MANIFEST,
  parseBundleJson,
  skillMarkdownName,
  validateBundle,
  type BundleAgent,
  type BundleBudget,
  type BundleDepartment,
  type BundleMcpServer,
  type BundleOffer,
  type BundleSkill,
  type SkillSource,
  type TemplateBundle,
} from './templates';
export {
  BLUEPRINT_FORMAT,
  BLUEPRINT_FORMAT_VERSION,
  BLUEPRINT_LIMITS,
  BLUEPRINT_MANIFEST,
  blueprintCopyHandle,
  isBlueprintFilePath,
  parseBlueprintJson,
  validateBlueprint,
  type BlueprintAgent,
  type BlueprintBoard,
  type BlueprintCoordinator,
  type BlueprintFile,
  type BlueprintGoal,
  type BlueprintGoalStatus,
  type BlueprintNetworkMode,
  type BlueprintRoutine,
  type BlueprintSticker,
  type ProjectBlueprint,
} from './blueprints';
export {
  HOST_AREAS,
  HOST_HEALTH_STATES,
  isHostHealthState,
  normalizeHostHealthItem,
  worstHostHealth,
  type BuiltinHostArea,
  type HostAvailability,
  type HostCapability,
  type HostCapabilityContext,
  type HostHealthItem,
  type HostHealthState,
  type HostUnavailableReason,
} from './host';
export {
  BUILTIN_NOTIFICATION_CATEGORY_IDS,
  PUSH_URGENCIES,
  isPushUrgency,
  normalizeAlertItem,
  type AlertItem,
  type AlertSource,
  type AlertSourceContext,
  type AlertText,
  type BuiltinNotificationCategoryId,
  type NotificationAudience,
  type NotificationCategory,
  type PushUrgency,
} from './notifications';
export {
  definePlugin,
  type HelenaPlugin,
  type HostProcess,
  type PluginContext,
  type Registrar,
} from './plugin';
export {
  USAGE_LIMIT_NEAR_PERCENT,
  effectiveUsedPercent,
  normalizeUsageLimitSnapshot,
  snapshotState,
  windowKindOf,
  windowState,
  worstState,
  type UsageLimitAgentContext,
  type UsageLimitExtra,
  type UsageLimitObserver,
  type UsageLimitPollContext,
  type UsageLimitProbe,
  type UsageLimitSnapshot,
  type UsageLimitSource,
  type UsageLimitState,
  type UsageLimitUnavailable,
  type UsageLimitWindow,
  type UsageLimitWindowKind,
} from './usage-limits';
export { normalizeRuntimeAccount, type RuntimeAccount } from './runtime-account';
export {
  normalizeRuntimeLoginReport,
  runtimeLoginCondition,
  runtimeLoginNeedsOwner,
  type RuntimeLogin,
  type RuntimeLoginCondition,
  type RuntimeLoginPollContext,
  type RuntimeLoginReport,
  type RuntimeLoginSource,
  type RuntimeLoginState,
} from './runtime-logins';
export {
  LOCAL_AI_MODES,
  LOCAL_AI_PRIORITIES,
  LOCAL_AI_THINKING,
  LOCAL_AI_UNITS,
  LOCAL_MODEL_CAPABILITIES,
  LOCAL_NO_THINKING_SUFFIX,
  LOCAL_PROVIDER_PREFIX,
  classEvalVersion,
  classModes,
  isLocalProvider,
  isModelServerSlug,
  localModelId,
  localProviderName,
  localProviderWithoutThinking,
  localThinkingFields,
  median,
  normalizeLocalModel,
  parseLocalModelId,
  type LocalAiChatAnswer,
  type LocalAiChatRequest,
  type LocalAiEvalCaseResult,
  type LocalAiEvalContext,
  type LocalAiEvalResult,
  type LocalAiMode,
  type LocalAiPriority,
  type LocalAiTaskClass,
  type LocalAiThinking,
  type LocalAiUnit,
  type LocalModel,
  type LocalModelCapability,
  type ModelServerAudio,
  type ModelServerContext,
  type ModelServerLoad,
  type ModelServerStatus,
  type ModelServerType,
  type HermesHelperTask,
  type RuntimeLocalAi,
  type RuntimeModelServer,
} from './local-ai';
export {
  UPDATE_KINDS,
  UPDATE_RISKS,
  compareVersions,
  isNewerVersion,
  isPrerelease,
  isUpdateRisk,
  normalizeUpdateCandidate,
  updatePriority,
  type UpdateApplyContext,
  type UpdateApplyRequest,
  type UpdateApplyStarted,
  type UpdateCandidate,
  type UpdateCheckContext,
  type UpdateFetchOptions,
  type UpdateKind,
  type UpdateProgress,
  type UpdateRisk,
  type UpdateSource,
} from './updates';
export type {
  McpServerContribution,
  PluginEntries,
  PluginManifest,
  PluginPermissions,
  PluginProvides,
} from './manifest-types';
export {
  DECISION_PROTOCOLS,
  SYSTEM_ONE_MODELS_PATH,
  SYSTEM_ONE_PATH,
  systemOneUrl,
  type DecisionBackendPreset,
  type DecisionBackendType,
  type DecisionPolicyKind,
  type DecisionProtocol,
} from './decision-backends';
export {
  DECISION_STATUSES,
  decisionConfidence,
  decisionOptionIds,
  decisionQuestionProblem,
  isDecisionOptionId,
  type DecisionAnswer,
  type DecisionClass,
  type DecisionEvalCase,
  type DecisionEvalSet,
  type DecisionKind,
  type DecisionOption,
  type DecisionQuestion,
  type DecisionStatus,
} from './decisions';

export * from './escalation';
