import { expect, test } from 'bun:test';
import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import ts from 'typescript';

const root = resolve(import.meta.dir, '../../../..');
function files(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = resolve(dir, entry.name);
    return entry.isDirectory() ? files(path) : [path];
  });
}

test('owned prompt, bundle and tool texts have no legacy product name', () => {
  const paths = [
    ...files(resolve(root, 'bundles/agent-pool')).filter((path) => /\.(md|json)$/.test(path)),
    ...files(resolve(root, 'apps/api/src/scripts')).filter(
      (path) => path.endsWith('.ts') && !path.includes('__tests__') && !path.endsWith('.test.ts'),
    ),
    ...files(resolve(root, 'apps/api/src/modules')).filter(
      (path) => path.endsWith('.ts') && !path.includes('__tests__') && !path.endsWith('.test.ts'),
    ),
    ...files(resolve(root, 'packages/agent-runtime/src')).filter(
      (path) => path.endsWith('.ts') && !path.includes('__tests__') && !path.endsWith('.test.ts'),
    ),
    ...['tools.ts', 'oauth.ts'].map((path) =>
      resolve(root, 'packages/connectors/src/google', path),
    ),
    ...['tools.ts', 'server.ts', 'task/run.ts'].map((path) =>
      resolve(root, 'packages/browser-gateway/src', path),
    ),
    ...['tools.ts', 'connector.ts', 'client.ts'].map((path) =>
      resolve(root, 'packages/trading/src/alpaca', path),
    ),
    resolve(root, 'apps/api/src/scripts/agent-tuning/target.ts'),
    resolve(root, 'apps/api/src/modules/local-ai/evals.ts'),
  ];
  const violations: string[] = [];
  for (const path of paths) {
    const source = readFileSync(path, 'utf8');
    if (!path.endsWith('.ts')) {
      if (/\bHelenas?\b/.test(source)) violations.push(path.slice(root.length + 1));
      continue;
    }
    const ast = ts.createSourceFile(path, source, ts.ScriptTarget.Latest, true);
    function visit(node: ts.Node): void {
      const apiModule =
        path.includes('/apps/api/src/modules/') ||
        (path.includes('/apps/api/src/scripts/') && !path.endsWith('/agent-tuning/target.ts'));
      const promptModule =
        path.endsWith('/local-ai/evals.ts') ||
        /\/(?:[^/]*prompt|reflection|agent-team-contract)\.ts$/.test(path) ||
        path.includes('/agents/runtime-policy/');
      let parent: ts.Node | undefined = node.parent;
      let metadata = false;
      while (parent && !ts.isStatement(parent)) {
        if (
          ts.isPropertyAssignment(parent) &&
          /^(description|summary|title|system)$/.test(
            parent.name.getText(ast).replaceAll(/['"]/g, ''),
          )
        )
          metadata = true;
        parent = parent.parent;
      }
      if (
        (ts.isStringLiteralLike(node) ||
          ts.isTemplateHead(node) ||
          ts.isTemplateMiddle(node) ||
          ts.isTemplateTail(node)) &&
        (!apiModule || metadata || promptModule) &&
        /\bHelenas?\b/.test(
          node.text
            .replaceAll(/X-Helena-[A-Za-z-]+/g, '')
            .replaceAll("<!-- Generated by Helena from the agent's settings. -->", ''),
        )
      ) {
        violations.push(
          `${path.slice(root.length + 1)}:${ast.getLineAndCharacterOfPosition(node.getStart(ast)).line + 1}`,
        );
      }
      ts.forEachChild(node, visit);
    }
    visit(ast);
  }
  expect(violations).toEqual([]);
});
