# DKMS package of ryzen_smu (amkillam fork), written by Helena's fan-control installer.
# The project's Makefile picks the headers of TARGET; built with gcc, like Debian's kernel.
PACKAGE_NAME="ryzen_smu"
PACKAGE_VERSION="@VERSION@"
BUILT_MODULE_NAME[0]="ryzen_smu"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make TARGET=${kernelver} modules"
CLEAN="make TARGET=${kernelver} clean"
AUTOINSTALL="yes"
