import { createHash } from 'node:crypto';
import { db, aiAgent } from '@repo/db';
import { eq } from 'drizzle-orm';

import {
  getAgentById,
  type AgentRuntimeConflict,
  type AgentRuntimeInventory,
  type AgentRuntimePolicy,
  type AgentRuntimeState,
} from '../core/service';
import {
  attachmentPreamble,
  chartPreamble,
  projectInstructionsPreamble,
  projectsPreamble,
} from '../core/prompt/framing';
import type { RunnerAgent } from '../runner/service';
import { listAgentRuntimeSkills } from '../skills/service';
import { listAgentToolLinks } from '../tools/service';
import { agentRuntimeMcpServers } from '../mcp-servers/service';
import { structureSection } from './structure';

export async function runtimePolicySnapshot(agentRef: RunnerAgent) {
  const agent = await getAgentById(agentRef.id, agentRef.teamId);
  if (!agent) throw new Error('Agent not found');
  const [skills, tools, structure, mcpServers] = await Promise.all([
    listAgentRuntimeSkills(agent.id),
    listAgentToolLinks(agent.id),
    structureSection(agent),
    agentRuntimeMcpServers(agent.id),
  ]);
  const snapshot = {
    agent: { id: agent.id, name: agent.name, username: agent.username },
    instructions: agent.instructions,
    model: agent.model,
    memory: { enabled: agent.memoryEnabled, lastMessages: agent.memoryLastMessages },
    runtimePolicy: {
      ...agent.runtimePolicy,
      files: [
        {
          kind: 'instructions' as const,
          path: 'SOUL.md',
          content: soul(agentRef, agent, structure),
        },
      ],
    },
    projects: agent.projects.map(({ id, key, name, instructions }) => ({
      id,
      key,
      name,
      instructions,
    })),
    skills,
    configuredTools: tools.map(({ id, toolKey, integrationKey }) => ({
      id,
      toolKey,
      integrationKey,
    })),
    mcpServers,
  };
  // Prefix the digest so API clients consistently keep this as an opaque string.
  // Eden's response parser treats a bare 64-character digest as an encoded value.
  const revision = `sha256:${createHash('sha256').update(JSON.stringify(snapshot)).digest('hex')}`;
  return { revision, ...snapshot };
}

// Ends the operator's own SOUL.md, so a SOUL.md that was changed outside Plan can be
// taken over without what Plan adds after it. The web app splits at the same line.
const SOUL_GENERATED_MARKER = "<!-- Generated by Plan from the agent's settings. -->";

// The SOUL.md the runner writes into the agent's Hermes home. Hermes loads it into every
// session, chat and run alike, so this is where the agent's identity, its instructions,
// the projects it works in, its place in the team's structure and the conventions of
// the app reach it. The operator's own SOUL.md comes first, then every file below
// instructions/, then what Plan knows.
function soul(
  agent: RunnerAgent,
  config: { name: string; runtimePolicy: AgentRuntimePolicy },
  structure: string,
): string {
  const files = [...config.runtimePolicy.files].sort((a, b) => a.path.localeCompare(b.path));
  const own = files.find((file) => file.path === 'SOUL.md')?.content.trim();
  const instructions = agent.instructions?.trim();
  return [
    own ||
      `You are ${config.name} (@${agent.username}), an agent of this team. Be direct: a short ` +
        'question gets a short answer, and finished work gets a short report of what changed, ' +
        'what is verified and what is left.',
    SOUL_GENERATED_MARKER,
    ...files
      .filter((file) => file.path !== 'SOUL.md' && file.content.trim())
      .map((file) => `## ${file.path}\n\n${file.content.trim()}`),
    ...(instructions ? [`## Instructions\n\n${instructions}`] : []),
    projectsPreamble(agent.projects).trim(),
    ...agent.projects.map((project) => projectInstructionsPreamble(project).trim()),
    structure,
    chatPreamble().trim(),
    blockedPreamble(),
    approvalPreamble(),
    chartPreamble().trim(),
    attachmentPreamble().trim(),
  ]
    .filter(Boolean)
    .join('\n\n')
    .concat('\n');
}

// A run's task states that it is autonomous; a chat message arrives without such a frame,
// so the difference is spelled out here once.
function chatPreamble(): string {
  return [
    '## Chat',
    'A message without a run frame comes from a person chatting with you in the app who is',
    'waiting for your reply. Answer them directly and keep it short. Ask a clarifying',
    'question when you genuinely need one; in an autonomous run nobody is there to answer it.',
  ].join('\n');
}

function blockedPreamble(): string {
  return [
    '## When you are blocked',
    'When a task cannot go on without a decision or information only a person can give, call',
    'mark_issue_blocked on its issue with one clear question instead of guessing. It adds the',
    'Blocked label, posts the question and notifies the person you report to, and your run ends',
    'as blocked. Then stop and end your turn. A reply to that comment starts you again; remove',
    'the Blocked label when you continue. Do not use it for a problem you can solve yourself.',
  ].join('\n');
}

function approvalPreamble(): string {
  return [
    '## Approvals',
    'Before you send, publish, pay or delete anything outside Plan, call request_approval',
    'with the action, its kind and every detail the owner needs to decide, then end the run',
    'without taking the action. Plan starts a new run of yours with the decision: act only',
    'on an approved request, exactly as approved. get_approval reads a request.',
  ].join('\n');
}

export async function reportRuntimeState(
  agentId: number,
  state: Omit<AgentRuntimeState, 'reportedAt' | 'conflicts' | 'inventory'> & {
    conflicts?: AgentRuntimeConflict[];
    inventory?: AgentRuntimeInventory;
  },
): Promise<AgentRuntimeState> {
  const value: AgentRuntimeState = {
    ...state,
    conflicts: state.conflicts ?? [],
    inventory: state.inventory ?? null,
    reportedAt: new Date().toISOString(),
  };
  await db
    .update(aiAgent)
    .set({ runtimeState: value, lastSeenAt: new Date() })
    .where(eq(aiAgent.id, agentId));
  return value;
}
