import { createHash } from 'node:crypto';
import { db, aiAgent } from '@repo/db';
import { eq } from 'drizzle-orm';
import { HttpError } from '#shared/lib';

import {
  getAgentById,
  type AgentRuntimeConflict,
  type AgentRuntimeInventory,
  type AgentRuntimePolicy,
  type AgentRuntimeState,
} from '../core/service';
import {
  attachmentPreamble,
  chartPreamble,
  projectInstructionsPreamble,
  projectsPreamble,
} from '../core/prompt/framing';
import type { RunnerAgent } from '../runner/service';
import { listAgentRuntimeSkills } from '../skills/service';
import { listAgentToolLinks } from '../tools/service';
import { agentRuntimeMcpServers } from '../mcp-servers/service';
import { hasWebLoginGrant } from '../credentials/service';
import {
  completeRuntimeActions,
  pendingRuntimeActions,
  type LearnedSkill,
  type RuntimeActionResult,
} from '../learning/service';
import { areasSection } from './areas';
import { agentVaultAccess, knowledgeSection } from './knowledge';
import { structureSection } from './structure';

export async function runtimePolicySnapshot(agentRef: RunnerAgent) {
  const agent = await getAgentById(agentRef.id, agentRef.teamId);
  if (!agent) throw new Error('Agent not found');
  const [skills, tools, structure, areas, mcpServers, webLogins, vaultAccess, actions] =
    await Promise.all([
      listAgentRuntimeSkills(agent.id),
      listAgentToolLinks(agent.id),
      structureSection(agent),
      areasSection(agent),
      agentRuntimeMcpServers(agent.id),
      hasWebLoginGrant(agent.id),
      agentVaultAccess(agentRef.userId),
      pendingRuntimeActions(agent.id),
    ]);
  const snapshot = {
    agent: { id: agent.id, name: agent.name, username: agent.username },
    instructions: agent.instructions,
    model: agent.model,
    memory: { enabled: agent.memoryEnabled, lastMessages: agent.memoryLastMessages },
    runtimePolicy: {
      ...agent.runtimePolicy,
      files: [
        {
          kind: 'instructions' as const,
          path: 'SOUL.md',
          content: soul(agentRef, agent, {
            structure,
            areas,
            knowledge: knowledgeSection(vaultAccess),
            webLogins,
          }),
        },
      ],
    },
    projects: agent.projects.map(({ id, key, name, instructions }) => ({
      id,
      key,
      name,
      instructions,
    })),
    skills,
    configuredTools: tools.map(({ id, toolKey, integrationKey }) => ({
      id,
      toolKey,
      integrationKey,
    })),
    mcpServers,
    webLogins,
    vaultAccess,
    learning: {
      enabled: agent.runtimePolicy.learning ?? true,
      curator: agent.runtimePolicy.curator ?? false,
    },
    actions,
  };
  // Prefix the digest so API clients consistently keep this as an opaque string.
  // Eden's response parser treats a bare 64-character digest as an encoded value.
  const revision = `sha256:${createHash('sha256').update(JSON.stringify(snapshot)).digest('hex')}`;
  return { revision, ...snapshot };
}

// Ends the operator's own SOUL.md, so a SOUL.md that was changed outside Helena can be
// taken over without what Helena adds after it. The web app splits at the same line.
const SOUL_GENERATED_MARKER = "<!-- Generated by Helena from the agent's settings. -->";

// The SOUL.md the runner writes into the agent's Hermes home. Hermes loads it into every
// session, chat and run alike, so this is where the agent's identity, its instructions,
// the projects it works in, its place in the team's structure and the conventions of
// the app reach it. The operator's own SOUL.md comes first, then every file below
// instructions/, then what Helena knows.
function soul(
  agent: RunnerAgent,
  config: { name: string; runtimePolicy: AgentRuntimePolicy },
  sections: { structure: string; areas: string; knowledge: string; webLogins: boolean },
): string {
  const { structure, areas, knowledge, webLogins } = sections;
  const files = [...config.runtimePolicy.files].sort((a, b) => a.path.localeCompare(b.path));
  const own = files.find((file) => file.path === 'SOUL.md')?.content.trim();
  const instructions = agent.instructions?.trim();
  return [
    own ||
      `You are ${config.name} (@${agent.username}), an agent of this team. Be direct: a short ` +
        'question gets a short answer, and finished work gets a short report of what changed, ' +
        'what is verified and what is left.',
    SOUL_GENERATED_MARKER,
    ...files
      .filter((file) => file.path !== 'SOUL.md' && file.content.trim())
      .map((file) => `## ${file.path}\n\n${file.content.trim()}`),
    ...(instructions ? [`## Instructions\n\n${instructions}`] : []),
    projectsPreamble(agent.projects).trim(),
    ...agent.projects.map((project) => projectInstructionsPreamble(project).trim()),
    areas,
    knowledge,
    structure,
    chatPreamble().trim(),
    blockedPreamble(),
    approvalPreamble(),
    ...(webLogins ? [webLoginPreamble()] : []),
    chartPreamble().trim(),
    attachmentPreamble().trim(),
  ]
    .filter(Boolean)
    .join('\n\n')
    .concat('\n');
}

// A run's task states that it is autonomous; a chat message arrives without such a frame,
// so the difference is spelled out here once.
function chatPreamble(): string {
  return [
    '## Chat',
    'A message without a run frame comes from a person chatting with you in the app who is',
    'waiting for your reply. Answer them directly and keep it short. Ask a clarifying',
    'question when you genuinely need one; in an autonomous run nobody is there to answer it.',
  ].join('\n');
}

function blockedPreamble(): string {
  return [
    '## When you are blocked',
    'When a task cannot go on without a decision or information only a person can give, call',
    'mark_issue_blocked on its issue with one clear question instead of guessing. It adds the',
    'Blocked label, posts the question and notifies the person you report to, and your run ends',
    'as blocked. Then stop and end your turn. A reply to that comment starts you again; remove',
    'the Blocked label when you continue. Do not use it for a problem you can solve yourself.',
  ].join('\n');
}

function approvalPreamble(): string {
  return [
    '## Approvals',
    'Before you send, publish, pay or delete anything outside Plan, call request_approval',
    'with the action, its kind and every detail the owner needs to decide, then end the run',
    'without taking the action. Plan starts a new run of yours with the decision: act only',
    'on an approved request, exactly as approved. get_approval reads a request.',
  ].join('\n');
}

// Hermes fills a login from its vault without the model seeing the password. What the
// vault cannot fill, the owner does in the project's live browser, whose profile keeps
// the session for the next run.
function webLoginPreamble(): string {
  return [
    '## Website logins',
    'The website logins granted to you are in your Hermes vault. browser_vault_list names',
    'them. Type the username yourself, fill the password with browser_vault_fill and a',
    'verification code with browser_vault_enter_code. You never see a password; never ask',
    'anyone for one. When a site asks for what the vault cannot fill (a captcha, a passkey,',
    'a code sent by SMS or mail, a confirmation in an app), call request_approval with kind',
    'other, the action "Log in to <site> in the project browser" and what the site asks',
    'for, then end the run. The owner logs in in the live browser of the project, which',
    'keeps the session, and Plan starts a new run of yours once the owner approves. In a',
    'chat, tell the person instead.',
  ].join('\n');
}

// Hermes' own scheduler, which the runner never passes on: Plan schedules work through its
// routines, so the toggle for it is not offered.
const WITHHELD_TOOLSETS = ['cronjob'];

// What the learned skills of one report may hold together, beyond the bounds of each.
const MAX_LEARNED_CHARS = 2 * 1024 * 1024;

export async function reportRuntimeState(
  agentId: number,
  report: Omit<AgentRuntimeState, 'reportedAt' | 'conflicts' | 'restored' | 'inventory'> & {
    conflicts?: AgentRuntimeConflict[];
    restored?: string[];
    inventory?: AgentRuntimeInventory;
    learnedSkills?: LearnedSkill[];
    actions?: RuntimeActionResult[];
  },
): Promise<AgentRuntimeState> {
  const { learnedSkills = [], actions = [], ...state } = report;
  const learnedChars = learnedSkills.reduce(
    (sum, skill) =>
      sum + skill.markdown.length + skill.files.reduce((n, file) => n + file.content.length, 0),
    0,
  );
  if (learnedChars > MAX_LEARNED_CHARS) throw new HttpError(413, 'Learned skills are too large');
  const inventory = state.inventory;
  const value: AgentRuntimeState = {
    ...state,
    conflicts: state.conflicts ?? [],
    restored: state.restored ?? [],
    inventory: inventory
      ? {
          ...inventory,
          toolsets: inventory.toolsets.filter((name) => !WITHHELD_TOOLSETS.includes(name)),
        }
      : null,
    reportedAt: new Date().toISOString(),
  };
  await db
    .update(aiAgent)
    .set({ runtimeState: value, runtimeLearnedSkills: learnedSkills, lastSeenAt: new Date() })
    .where(eq(aiAgent.id, agentId));
  await completeRuntimeActions(agentId, actions);
  return value;
}
