'use client';

import { TriangleAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { AgentRuntimeConflict } from '@/lib/api/endpoints/agents';

// The line the API puts after the operator's own SOUL.md (SOUL_GENERATED_MARKER in the
// api's runtime-policy service).
const GENERATED_MARKER = "<!-- Generated by Plan from the agent's settings. -->";

// The part of a changed SOUL.md the operator owns: what stands before that line.
function ownSoulContent(content: string): string {
  return content.split(GENERATED_MARKER)[0].trim();
}

// Files the runtime found changed outside Plan, for instance by Hermes itself. The
// runtime kept each changed version next to the file and wrote Plan's. A changed SOUL.md
// can be taken over, which makes it Plan's version for the next sync; a changed skill
// file is kept in the skill library instead.
export default function AgentRuntimeConflicts({
  conflicts,
  onTakeOver,
}: {
  conflicts: AgentRuntimeConflict[];
  onTakeOver: (content: string) => void;
}) {
  if (conflicts.length === 0) return null;
  return (
    <div className="space-y-2 rounded-md border border-amber-500/40 bg-amber-500/5 p-3">
      <p className="flex items-center gap-2 text-sm font-medium">
        <TriangleAlert className="size-4 text-amber-600" />
        Changed outside Plan
      </p>
      <p className="text-xs text-muted-foreground">
        The runtime replaced these files with the version stored here and kept the changed version
        next to them.
      </p>
      {conflicts.map((conflict) => (
        <div key={conflict.path} className="space-y-1.5">
          <div className="flex items-center justify-between gap-2">
            <code className="text-xs">{conflict.path}</code>
            {conflict.path === 'SOUL.md' ? (
              <Button
                type="button"
                size="sm"
                variant="outline"
                onClick={() => onTakeOver(ownSoulContent(conflict.content))}
              >
                Take over
              </Button>
            ) : (
              <span className="text-xs text-muted-foreground">Edit it in the skill library</span>
            )}
          </div>
          <pre className="max-h-40 overflow-auto rounded bg-muted p-2 text-xs whitespace-pre-wrap">
            {conflict.content}
          </pre>
        </div>
      ))}
    </div>
  );
}
