'use client';

import { Notice, Stack, CodeBlock } from '@/design-system';
import { TriangleAlert } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { Button } from '@/components/ui/button';
import type { AgentRuntimeConflict } from '@/lib/api/endpoints/agents';

// The line the API puts after the operator's own SOUL.md (SOUL_GENERATED_MARKER in the
// api's runtime-policy service).
const GENERATED_MARKER = "<!-- Generated by Helena from the agent's settings. -->";

// The part of a changed SOUL.md the operator owns: what stands before that line.
function ownSoulContent(content: string): string {
  return content.split(GENERATED_MARKER)[0].trim();
}

// Files the runtime found changed outside Helena, for instance by Hermes itself. The
// runtime kept each changed version next to the file and wrote Helena's. A changed
// SOUL.md can be taken over, which makes it Helena's version for the next sync; a
// changed skill file is kept in the skill library instead.
export default function AgentRuntimeConflicts({
  conflicts,
  onTakeOver,
}: {
  conflicts: AgentRuntimeConflict[];
  onTakeOver: (content: string) => void;
}) {
  const t = useTranslations('teams.agents.runtimeConflicts');
  if (conflicts.length === 0) return null;
  return (
    <Notice tone="warning" icon={<TriangleAlert />} title={t('title')}>
      <Stack gap={2}>
        <p>{t('description')}</p>
        {conflicts.map((conflict) => (
          <div key={conflict.path} className="space-y-1.5">
            <div className="flex items-center justify-between gap-2">
              <code className="text-xs">{conflict.path}</code>
              {conflict.path === 'SOUL.md' ? (
                <Button
                  type="button"
                  size="sm"
                  variant="outline"
                  onClick={() => onTakeOver(ownSoulContent(conflict.content))}
                >
                  {t('takeOver')}
                </Button>
              ) : (
                <span className="text-xs text-muted-foreground">{t('editInLibrary')}</span>
              )}
            </div>
            <CodeBlock>{conflict.content}</CodeBlock>
          </div>
        ))}
      </Stack>
    </Notice>
  );
}
